name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Deploy Lambda function
      env:
        AWS_REGION: your-aws-region
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FUNCTION_NAME: your-lambda-function-name
      run: |
        aws lambda update-function-code --region $AWS_REGION --function-name $FUNCTION_NAME --zip-file fileb://my-lambda-function.zip
