name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt    

      - name: Run PyTests
        run: pytest

  deplpy-lambda:
    runs-on: ubuntu-latest
    needs: [run-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create zip file
        run: |
          cd lambda_source
          zip -r ../lambda.zip .
      - name: Upload zip file as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda-zip
          path: lambda.zip
      - name: Deploy Lambda function
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FUNCTION_NAME: GitActionsTestr
        run: |
          aws lambda update-function-code --region $AWS_REGION --function-name $FUNCTION_NAME --zip-file fileb://lambda.zip


      